config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :kittens
  root to: "kittens#index"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, presence: true, length: {in: 4..10}
  validates :age, presence: true, comparison: { greater_than: 0 }
  validates :cuteness, presence: true, comparison: { greater_than: 0, less_than_or_equal_to: 10 }
  validates :softness, presence: true, comparison: { greater_than: 0, less_than_or_equal_to: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html
      format.json { render json: @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      flash[:success] = "Congrats on your new cat!"
      redirect_to @kitten
    else
      flash.now[:error] = "Fix your mistakes please!"
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])
    if @kitten.update(kitten_params)
      flash[:success] = "Changes Saved successfully!"
      redirect_to @kitten
    else
      flash.now[:error] = "Fix your mistakes please!"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy
    flash[:success] = "Successfully Removed!"
    redirect_to :root
  end

  private

  def kitten_params
    params.expect(kitten: [ :name, :age, :cuteness, :softness ])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_kitten_form.html.erb
<%= form_with model: @kitten do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>
  <div>
    <%= form.label :cuteness %>
    <%= form.number_field :cuteness, :step => "0.1" %>
  </div>
  <div>
    <%= form.label :softness %>
    <%= form.number_field :softness, :step => "0.1" %>
  </div>
  <%= form.submit "Confirm" %>
<% end %>

app/views/kittens/edit.html.erb
<h1>Edit this Kitten:</h1>

<%= render "kitten_form" %>
<div><%= link_to "Remove Kitten", @kitten, data: { turbo_method: "delete" } %></div>

app/views/kittens/index.html.erb
<h1>Our Kittens</h1>
<h2>Cuteness and Softness on a Scale of 10</h2>

<ul>
  <% if @kittens %>
    <% @kittens.each do |k| %>
      <li>
        <div>
          <%= k.name %>
          <%= link_to "View this Kitten", k %>
          <%= link_to "Remove Kitten", k, data: { turbo_method: "delete" } %>
        </div>
      </li>
    <% end %>
  <% else %>
    <h3>No Kittens Right Now! <%= link_to "Create a Kitten", new_kitten_path %></h3>
  <% end %>
</ul>
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>
<%= link_to "Create a Kitten", new_kitten_path %>

app/views/kittens/new.html.erb
<h1>Create a new Kitten:</h1>

<%= render partial: "kittens/kitten_form", :locals => { :kitten => @kitten } %>
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

app/views/kittens/show.html.erb
<h1><%= @kitten.name %>:</h1>

<ul>
  <li>Age: <%= @kitten.age %></li>
  <li>Cuteness: <%= @kitten.cuteness %></li>
  <li>Softness: <%= @kitten.softness %></li>
</ul>

<div><%= link_to "Change", edit_kitten_path %></div>
<div><%= link_to "Home", :root %></div>
<div><%= link_to "Remove Kitten", @kitten, data: { turbo_method: "delete" } %></div>
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Kittens" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>